### ISSUE TITLE
Build problem el/6 (centos/rhel) 

### ISSUE THREAD

**Issue by Sulverus** [tarantool/nginx_upstream_module#46]
Nginx can't see tnt_* options, solved with disabling new style build in `config`:
```
#if [ ! -n "$ngx_module_link" ]; then
# __old_style_build=no
#fi
```
Probably, new style build is incompatible with el/6

**Comment by bigbes** [comment]
Also it's incompatible with ubuntu 14.04 / nginx 1.9.3

With best regards, Eugene.

2016-07-15 21:56 GMT+03:00 Andrew <notifications@github.com>:

**Comment by dedok** [comment]
Fix: via using portable 'test ...' instead of [ ].
Also I added pretty big test, see test/ngx_versions.sh and test/ngx_versions_list.
If you wish to add any version in testing, then feel free just do it! For add new version just add version TAG in file test/ngx_versions_list.
For start testing run - test/ngx_versions.sh.
